"""cu25 pago en caja - monto recibido y vuelto

Revision ID: 0945915659aa
Revises: 5389dd4799b5
Create Date: 2026-09-13 03:52:37.121988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0945915659aa'
down_revision: Union[str, Sequence[str], None] = '5389dd4799b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pago', sa.Column('monto_recibido', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('pago', sa.Column('vuelto', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pago', 'vuelto')
    op.drop_column('pago', 'monto_recibido')
    # ### end Alembic commands ###
