"""sucursales: tabla sucursal + FK usuario.sucursal_id

Revision ID: 0e8ce19f15ff
Revises: b2fee07c60f2
Create Date: 2026-09-10 12:27:14.615917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e8ce19f15ff'
down_revision: Union[str, Sequence[str], None] = 'b2fee07c60f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('horario_atencion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sucursal_ciudad'), 'sucursal', ['ciudad'], unique=False)
    op.create_index(op.f('ix_sucursal_nombre'), 'sucursal', ['nombre'], unique=False)
    op.create_foreign_key('fk_usuario_sucursal_id', 'usuario', 'sucursal', ['sucursal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuario_sucursal_id', 'usuario', type_='foreignkey')
    op.drop_index(op.f('ix_sucursal_nombre'), table_name='sucursal')
    op.drop_index(op.f('ix_sucursal_ciudad'), table_name='sucursal')
    op.drop_table('sucursal')
    # ### end Alembic commands ###
