"""producto: precio_compra + precio_base nullable

Revision ID: 48aa62e8941c
Revises: d93e281b332f
Create Date: 2026-09-10 21:04:59.851903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '48aa62e8941c'
down_revision: Union[str, Sequence[str], None] = 'd93e281b332f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('producto', 'precio_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('producto', 'precio_base',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('producto', 'precio_compra')
    # ### end Alembic commands ###
