"""envio: direccion de entrega y sucursal por linea de venta

Revision ID: 7436dba71c83
Revises: c1694b01d765
Create Date: 2026-09-19 18:45:44.968476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7436dba71c83'
down_revision: Union[str, Sequence[str], None] = 'c1694b01d765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venta', sa.Column('direccion_entrega', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('venta', sa.Column('referencia_entrega', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True))
    op.add_column('venta_detalle', sa.Column('sucursal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_venta_detalle_sucursal_id', 'venta_detalle', 'sucursal', ['sucursal_id'], ['id']
    )
    # Antes toda la venta salía de una sola sucursal: la de la propia venta.
    op.execute(
        "UPDATE venta_detalle SET sucursal_id = venta.sucursal_id "
        "FROM venta WHERE venta.id = venta_detalle.venta_id"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_venta_detalle_sucursal_id', 'venta_detalle', type_='foreignkey')
    op.drop_column('venta_detalle', 'sucursal_id')
    op.drop_column('venta', 'referencia_entrega')
    op.drop_column('venta', 'direccion_entrega')
    # ### end Alembic commands ###
