"""proveedores: tabla proveedor + FK usuario.proveedor_id

Revision ID: 899a94deba55
Revises: 0e8ce19f15ff
Create Date: 2026-09-10 12:52:03.224272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '899a94deba55'
down_revision: Union[str, Sequence[str], None] = '0e8ce19f15ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('contacto', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proveedor_nombre_empresa'), 'proveedor', ['nombre_empresa'], unique=False)
    op.create_foreign_key('fk_usuario_proveedor_id', 'usuario', 'proveedor', ['proveedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuario_proveedor_id', 'usuario', type_='foreignkey')
    op.drop_index(op.f('ix_proveedor_nombre_empresa'), table_name='proveedor')
    op.drop_table('proveedor')
    # ### end Alembic commands ###
