"""reservas: finalizar reserva (venta de reserva y cantidad llevada)

Revision ID: 9c4a57f67966
Revises: 7436dba71c83
Create Date: 2026-09-20 02:10:13.287402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9c4a57f67966'
down_revision: Union[str, Sequence[str], None] = '7436dba71c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserva_detalle', sa.Column('cantidad_llevada', sa.Integer(), nullable=True))
    op.add_column('venta', sa.Column('reserva_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_venta_reserva_id', 'venta', 'reserva', ['reserva_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_venta_reserva_id', 'venta', type_='foreignkey')
    op.drop_column('venta', 'reserva_id')
    op.drop_column('reserva_detalle', 'cantidad_llevada')
    # ### end Alembic commands ###
