"""producto_variante imagen_url

Revision ID: aa1847411c0f
Revises: be206c46b0eb
Create Date: 2026-09-11 00:11:27.990691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa1847411c0f'
down_revision: Union[str, Sequence[str], None] = 'be206c46b0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto_variante', sa.Column('imagen_url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto_variante', 'imagen_url')
    # ### end Alembic commands ###
