"""cu33: promociones y precio original en venta_detalle

Revision ID: c1694b01d765
Revises: e151a1f34fc2
Create Date: 2026-09-18 23:00:57.278846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1694b01d765'
down_revision: Union[str, Sequence[str], None] = 'e151a1f34fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tipo_descuento', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promocion_producto',
    sa.Column('promocion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promocion.id'], ),
    sa.PrimaryKeyConstraint('promocion_id', 'producto_id')
    )
    op.add_column('venta_detalle', sa.Column('precio_original', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('venta_detalle', sa.Column('promocion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_venta_detalle_promocion_id', 'venta_detalle', 'promocion', ['promocion_id'], ['id']
    )
    # Las ventas anteriores a las promociones se vendieron sin descuento.
    op.execute("UPDATE venta_detalle SET precio_original = precio_unitario")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_venta_detalle_promocion_id', 'venta_detalle', type_='foreignkey')
    op.drop_column('venta_detalle', 'promocion_id')
    op.drop_column('venta_detalle', 'precio_original')
    op.drop_table('promocion_producto')
    op.drop_table('promocion')
    # ### end Alembic commands ###
