"""catalogo: categoria, talla, color

Revision ID: ce48941251fe
Revises: 899a94deba55
Create Date: 2026-09-10 13:08:04.199612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ce48941251fe'
down_revision: Union[str, Sequence[str], None] = '899a94deba55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_nombre'), 'categoria', ['nombre'], unique=True)
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('codigo_hex', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_color_nombre'), 'color', ['nombre'], unique=True)
    op.create_table('talla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('valor', 'tipo', name='uq_talla_valor_tipo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talla')
    op.drop_index(op.f('ix_color_nombre'), table_name='color')
    op.drop_table('color')
    op.drop_index(op.f('ix_categoria_nombre'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
