"""ia: historial_interaccion y reporte_generado

Revision ID: e151a1f34fc2
Revises: 0945915659aa
Create Date: 2026-09-18 22:53:23.673183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e151a1f34fc2'
down_revision: Union[str, Sequence[str], None] = '0945915659aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte_generado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_reporte', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('formato_solicitud', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_generado_usuario_id'), 'reporte_generado', ['usuario_id'], unique=False)
    op.create_table('historial_interaccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('consulta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('respuesta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_interaccion_cliente_id'), 'historial_interaccion', ['cliente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_interaccion_cliente_id'), table_name='historial_interaccion')
    op.drop_table('historial_interaccion')
    op.drop_index(op.f('ix_reporte_generado_usuario_id'), table_name='reporte_generado')
    op.drop_table('reporte_generado')
    # ### end Alembic commands ###
