"""precio_compra por variante

Revision ID: ed962072a536
Revises: fd7a2ba1edd3
Create Date: 2026-09-12 23:41:07.960151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed962072a536'
down_revision: Union[str, Sequence[str], None] = 'fd7a2ba1edd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto_variante', sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto_variante', 'precio_compra')
    # ### end Alembic commands ###
