"""cu33: promociones por variante

Revision ID: f903284f7fd6
Revises: 9c4a57f67966
Create Date: 2026-09-20 16:03:28.598240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f903284f7fd6'
down_revision: Union[str, Sequence[str], None] = '9c4a57f67966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promocion_variante',
    sa.Column('promocion_id', sa.Integer(), nullable=False),
    sa.Column('variante_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promocion_id'], ['promocion.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['producto_variante.id'], ),
    sa.PrimaryKeyConstraint('promocion_id', 'variante_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('promocion_variante')
    # ### end Alembic commands ###
